workflows:
  android-release:
    name: Android Release
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        GCLOUD_SERVICE_ACCOUNT_JSON: $GCLOUD_SERVICE_ACCOUNT_JSON
    scripts:
      - flutter pub get
      - flutter build apk --release
      - bash upload_apk.sh
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk