workflows:
  android-release:
    name: Android Release
    max_build_duration: 60
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
    environment:
      flutter: stable
      groups:
        - SECRET
      vars:
        GCLOUD_SERVICE_ACCOUNT_JSON: Encrypted(...)
    scripts:
      - flutter pub get
      - flutter build apk --release
      - bash upload_apk.sh
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk